default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  user: myapp
  password: password1
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: admin-task_development

test:
  <<: *default
  database: admin-task_test

production:
  <<: *default
  database: admin-task_production
  username: admin-task
  password: <%= ENV['ADMIN-TASK_DATABASE_PASSWORD'] %>
